name: $(BuildID)
trigger:
    batch: true
    branches:
      include:
      - '*'
#config
variables:
  skip: false #edit


jobs:
  - job: Run_App
    displayName: CI_CD
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
    - bash: |
        cd $(System.DefaultWorkingDirectory)/01_api && docker build -t gabrielstar/index.js .
      displayName: Build
      condition: not(eq(variables.skip, false))

    - bash: |
        docker run --name index.js -d --rm -p 3000:3000 gabrielstar/index.js
      displayName: Run
      condition: not(eq(variables.skip, false))

    - bash: |
        mkdir -p $(System.DefaultWorkingDirectory)/02_k6/data
        ls -alh $(System.DefaultWorkingDirectory)/02_k6/
        cd $(System.DefaultWorkingDirectory)/02_k6
        echo "Running diagnostics"
        docker run --entrypoint="" -v $(System.DefaultWorkingDirectory)/02_k6/data:/home/k6 loadimpact/k6 sh -c "whoami && cd ~ && pwd && ls -alh ~/ && touch ~/foo"
        ls -alh $(System.DefaultWorkingDirectory)/02_k6/data
      displayName: Diagnostics

    - pwsh: |
          mkdir -p $(System.DefaultWorkingDirectory)/02_k6/data
          cd $(System.DefaultWorkingDirectory)/02_k6
          echo "Running diagnostics"
          docker run --entrypoint="" -v $(System.DefaultWorkingDirectory)/02_k6/data:/data loadimpact/k6 sh -c "ls -alh && touch /data/foo"
          ls -alh $(System.DefaultWorkingDirectory)/02_k6/data
          cat script.js | `
              docker run -i -v $(System.DefaultWorkingDirectory)/02_k6/data:/home/k6 `
                  loadimpact/k6 run `
                      --summary-export=/data/perf-test-results.json `
                      --vus 2 `
                      --tag user=cicd `
                      --out csv=/home/k6/results.csv `
                      --duration 5s -
      displayName: "Performance Tests"