name: $(BuildID)
trigger:
    batch: true
    branches:
      include:
      - '*'
#config
variables:
  skip: true #edit


jobs:
  - job: Run_App
    displayName: CI_CD
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
    - bash: |
        mkdir -p $(System.DefaultWorkingDirectory)/02_k6/data
        chmod -R 0777 $(System.DefaultWorkingDirectory)/02_k6/data
        cd $(System.DefaultWorkingDirectory)/01_api
      displayName: Prepare

    - script: cd $(System.DefaultWorkingDirectory)/01_api && npm test
      displayName: Unit tests
      condition: not(eq(variables.skip, false))

    - script: npm run e2e-test
      displayName: Integration tests
      condition: not(eq(variables.skip, false))

    - bash: |
        cd $(System.DefaultWorkingDirectory)/01_api && docker build -t gabrielstar/index.js .
      displayName: Build
      condition: not(eq(variables.skip, false))

    - bash: |
        docker run --name index.js -d --rm -p 3000:3000 gabrielstar/index.js
      displayName: Run
      condition: not(eq(variables.skip, false))

    - pwsh: |
          cd $(System.DefaultWorkingDirectory)/02_k6
          (Get-Content -Path .\script.js) -replace 'host.docker.internal','localhost'  | `
              docker run -i -v $(System.DefaultWorkingDirectory)/02_k6/data:/home/k6 `
                  loadimpact/k6 run `
                      --summary-export=/home/k6/perf-test-results.json `
                      --vus 2 `
                      --tag user=cicd `
                      --out csv=/home/k6/results.csv `
                      --duration 5s -
      displayName: "Performance Tests"