# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources
name: $(BuildID)
trigger: none
#config
variables:
  flag: default #edit


jobs:
  - job: Run App
    displayName: CI_CD
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
    - bash: |
          cd $(System.DefaultWorkingDirectory)
          ls $(System.DefaultWorkingDirectory)
          cd 01_api
          ls $(System.DefaultWorkingDirectory)
          docker build -t gabrielstar/index.js .
      displayName: Build

    - bash: |
        docker run --name index.js -d --rm -p 3000:3000 gabrielstar/index.js
      displayName: Run

    - pwsh: |
        cd 02_k6
          $user=$env:UserName
          cat $PSScriptRoot/script.js | `
              docker run -i -v ${PSScriptRoot}:/data `
                  loadimpact/k6 run `
                      --summary-export=/data/perf-test-results.json `
                      --vus 2 `
                      --tag user=$user `
                      --out csv=/data/results.csv `
                      --duration 5s -